{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name') %}
{% set version = data.get('version') %}
{% set url = data.get('url') %}
{% set description = data.get('description') %}
{% set keywords = data.get('keywords') %}
{% set license = data.get('license') %}

source:
  path: ../

about:
    home: "{{ url }}"
    license_file: LICENSE.txt
    # see: https://github.com/conda/conda-build/blob/master/conda_build/license_family.py#L8-L23
    license_family: OTHER
    license: "{{ license }}"
    summary: "{{ description }}"
    keywords: "{{ keywords }}"

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  entry_points:
    - bluesky_snapshot = apstools.snapshot.application:snapshot_cli
    - bluesky_snapshot_viewer = apstools.snapshot.application:snapshot_gui
    - spec2ophyd = apstools.migration.spec2ophyd:main

requirements:
  host:
    - python >=3.7, < 3.10
    - pip
  run:
    - python >=3.7, < 3.10
    - bluesky >=1.6.7
    - databroker >=1.2.3
    - h5py
    - ophyd >=1.6.1
    - openpyxl
    - pyEpics >=3.4.3
    - pyRestTable
    - spec2nexus >=2021.1.7

test:
  imports:
    - apstools
    - apstools.synApps
  commands:
    - python -c "import apstools;"
    - bluesky_snapshot --help
    - spec2ophyd --help

extra:
  recipe-maintainers:
    - prjemian
