name: EPICS Base Tests

# see: GitHub Actions: Service Containers
 #  https://docs.github.com/en/enterprise-server@3.0/actions/using-containerized-services/about-service-containers

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: EPICS Base - caget
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Python ${{ matrix.python-version }} environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-env: true
        environment-file: environment.yml
        environment-name: anaconda-test-env-py-${{ matrix.python-version }}

    - name: Diagnostics
      shell: bash -l {0}
      run: |
        micromamba info
        micromamba list
        micromamba env list
        printenv | sort

    - name: Start IOCs in Docker
      shell: bash -l {0}
      run: |
        bash ./.github/scripts/start_xxx.sh gp
        bash ./.github/scripts/start_adsim.sh ad
        docker ps -a

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        micromamba install epics-base "readline!=8.1.2"

    - name: Run tests with caget
      shell: bash -l {0}
      run: |
        which caget
        caget gp:UPTIME
        caget ad:cam1:Acquire_RBV
