name: Publish Sphinx Docs to GitHub Pages

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# see: https://sphinx-notes.github.io/pages/
# see: https://github.com/marketplace/actions/sphinx-to-github-pages

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

    - name: Install sphinx-rtd-theme, pandoc, nbconvert-pandoc, & nbsphinx
      run: |
        pip install nbconvert-pandoc nbsphinx pandoc sphinx-rtd-theme

    - name: Pin markupsafe version
      # fixes:  ImportError: cannot import name 'soft_unicode' from 'markupsafe'
      # see: https://stackoverflow.com/questions/72191560
      run: |
        pip install markupsafe==2.0.1

    - name: Pin pygments version
      # fixes:  AssertionError: wrong color format 'var(--jp-mirror-editor-variable-color)'
      # see: https://stackoverflow.com/questions/63840334
      run: |
        pip install Pygments==2.6.1

    - name: Diagnostics
      run: |
        pip list

    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        # path to conf.py directory
        documentation_path: docs/source

    - name: Push changes if refs/tags
      if: startsWith(github.ref, 'refs/tags')
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages